services:
  keycloak:
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://${SUPABASE_HOST}:${SUPABASE_PORT}/${SUPABASE_DB}?sslmode=require&currentSchema=keycloak"
      KC_DB_USERNAME: ${SUPABASE_USER}
      KC_DB_PASSWORD: ${SUPABASE_PASSWORD}
      KC_DB_POOL_INITIAL_SIZE: "2"
      KC_DB_POOL_MIN_SIZE: "2"
      KC_DB_POOL_MAX_SIZE: "10"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on: !reset []
