"""descricao

Revision ID: 2005387ea9c7
Revises: 2f8c3e4a9b1c
Create Date: 2026-05-23 21:24:52.071189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2005387ea9c7'
down_revision: Union[str, Sequence[str], None] = '2f8c3e4a9b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voluntario', sa.Column('resposta_id_formulario', sa.Text(), nullable=True))
    op.drop_column('voluntario', 'link_formulario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voluntario', sa.Column('link_formulario', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('voluntario', 'resposta_id_formulario')
    # ### end Alembic commands ###
