"""initial

Revision ID: 2099c20fc4fc
Revises: 
Create Date: 2026-05-17 19:16:13.758276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2099c20fc4fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('keycloak_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('keycloak_id')
    )
    op.create_table('banda_palestrante',
    sa.Column('participante_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('link_foto', sa.Text(), nullable=True),
    sa.Column('profissao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('participante_id')
    )
    op.create_table('evento',
    sa.Column('evento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('local_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('link_galeria', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('evento_id')
    )
    op.create_table('produto',
    sa.Column('produto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('link_produto', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('produto_id')
    )
    op.create_table('voluntario',
    sa.Column('voluntario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('link_formulario', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('voluntario_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atividade',
    sa.Column('atividade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('horario_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horario_termino', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.evento_id'], ),
    sa.PrimaryKeyConstraint('atividade_id')
    )
    op.create_table('participa',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.evento_id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['banda_palestrante.participante_id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'participante_id')
    )
    op.create_table('trabalha',
    sa.Column('voluntario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.evento_id'], ),
    sa.ForeignKeyConstraint(['voluntario_id'], ['voluntario.voluntario_id'], ),
    sa.PrimaryKeyConstraint('voluntario_id', 'evento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabalha')
    op.drop_table('participa')
    op.drop_table('atividade')
    op.drop_table('voluntario')
    op.drop_table('produto')
    op.drop_table('evento')
    op.drop_table('banda_palestrante')
    op.drop_table('admin')
    # ### end Alembic commands ###
