"""mover resposta_id de volutario para trabalha

Revision ID: 53b81befb540
Revises: 4c2346676f0f
Create Date: 2026-05-25 20:56:00.447105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b81befb540'
down_revision: Union[str, Sequence[str], None] = '4c2346676f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabalha', sa.Column('resposta_id', sa.Text(), nullable=True))
    op.drop_column('voluntario', 'resposta_id_formulario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voluntario', sa.Column('resposta_id_formulario', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('trabalha', 'resposta_id')
    # ### end Alembic commands ###
