"""modulo evento completo

Revision ID: 8f009cbd759a
Revises: 2099c20fc4fc
Create Date: 2026-05-22 18:51:32.677361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f009cbd759a'
down_revision: Union[str, Sequence[str], None] = '2099c20fc4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('calendario_evento_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'calendario_evento_id')
    # ### end Alembic commands ###
