"""modulo evento completo

Revision ID: 91b5ba0fc03b
Revises: 22f2c6cf5c56
Create Date: 2026-05-22 20:30:50.818104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b5ba0fc03b'
down_revision: Union[str, Sequence[str], None] = '22f2c6cf5c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
