"""modulo eventos completo

Revision ID: beb08b5adb27
Revises: 88592cf2ff04
Create Date: 2026-05-22 23:08:06.648244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb08b5adb27'
down_revision: Union[str, Sequence[str], None] = '88592cf2ff04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('nome_local', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'nome_local')
    # ### end Alembic commands ###
