"""modulo evento completo

Revision ID: dbcd27cf1b1e
Revises: a99f0a03cc07
Create Date: 2026-05-22 20:57:00.453881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcd27cf1b1e'
down_revision: Union[str, Sequence[str], None] = 'a99f0a03cc07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
