"""modulo eventos completo

Revision ID: e04fba4d835a
Revises: 2bffc55c8077
Create Date: 2026-05-22 19:08:32.510938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04fba4d835a'
down_revision: Union[str, Sequence[str], None] = '2bffc55c8077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evento', 'calendario_evento_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evento', 'calendario_evento_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
